version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  contracts:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                working_directory: defi-contracts
                command: yarn install
            - run:
                working_directory: defi-contracts
                command: yarn test
workflows:
    contracts:
      jobs:
        - contracts